classDiagram
direction TB
    class Loaded_AudioFIL{
        +AudioArray, sample_rate
        +load_audio(file_path, target_sr=22050, mono=True)
    }

    class Beat{
    }

    class PeakPicking{
    }

    class AudioToMidi{
      +runfile(pathToFile)
    }

    class MidiExport{

    }

    class DrumKlassifierer{

    }

    class STFT{
        +calculated_stft
        +calculate_STFT(AudioArray, sample_rate, n_fft, hop_length)
        +plot_spectrogram(stft_result, sample_rate, hop_length, title="Spectrogram")
    }

    AudioToMidi *-- Audioloader
    AudioToMidi *-- BeatDetection
    AudioToMidi *-- MidiExport
    AudioToMidi *-- DrumKlassifierer
    BeatDetection *-- PeakPicking       